run:
  timeout: 10m

linters:
  enable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - misspell

issues:
  exclude-use-default: false

Linters-settings:
  govet:
    enable-all: true
